config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,   only: :show
    resources :categories, only: :show
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :related_products, -> (product) do
    includes(master: [:default_price, :images]).in_taxons(product.taxons).where.not(id: product).distinct
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.includes(root: { children: :children })
    @products = Spree::Product.in_taxon(@taxon).includes(master: [:default_price, :images])
    session[:taxon] = @taxon.id
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  include Spree::Core::ControllerHelpers::Pricing
  include Spree::Core::ControllerHelpers::Store

  LIMIT_NUMBER_OF_RELATED_PRODUCTS = 4

  def show
    @product = Spree::Product.friendly.find(params[:id])
    @images = @product.has_variants? ? @product.variant_images : @product.images
    @product_properties = @product.product_properties.includes(:property)
    @related_products = Spree::Product.related_products(@product).limit(LIMIT_NUMBER_OF_RELATED_PRODUCTS)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = {})
    base_title = "BIGBAG Store"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/potepan/products_helper.rb
module Potepan
  module ProductsHelper
    def options_text(product)
      variants = product.variants.includes(option_values: :option_type).with_prices(current_pricing_options).select do |variant|
        variant.option_values.any?
      end

      variants.map do |variant|
        values = variant.option_values.sort_by do |option_value|
          option_value.option_type.position
        end

        values.to_a.map! do |ov|
          "#{ov.option_type.presentation}: #{ov.presentation}"
        end

        values.to_sentence({ words_connector: ", ", two_words_connector: ", " })
      end
    end

    def quantities(product)
      product.stock_items.first.count_on_hand.times.map do |q|
        [q + 1, q + 1]
      end
    end
  end
end

app/views/layouts/_meta.html.erb
<%= csrf_meta_tags %>

<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_style.html.erb
<!-- PLUGINS CSS STYLE -->
<%= stylesheet_link_tag "application", :media => "all" %>

<!-- GOOGLE FONT -->
<%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield(:title) %></title>
    <%= render 'layouts/meta' %>
    <%= render 'layouts/style' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="main-wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= render 'shared/login_modal' %>
    <%= render 'shared/signup_modal' %>
    <%= render 'shared/product_modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_light_section.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <div class="page-title">
        <h2><%= taxon.name %></h2>
      </div>
    </div>
    <div class="col-xs-6">
      <ol class="breadcrumb pull-right">
        <li>
          <a href="index.html">Home</a>
        </li>
        <li>
          <a href="#">shop</a>
        </li>
        <li class="active"><%= taxon.name %></li>
      </ol>
    </div>
  </div>
</div>

app/views/potepan/categories/_product_main.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">並び替え</option>
      <option value="1">人気順</option>
      <option value="2">安い順</option>
      <option value="3">新着順</option>
      <option value="3">高い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
      <button type="button" class="btn btn-default" onclick="window.location.href='/sample/product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
    </div>
  </div>
</div>
<div class="row">
  <% products.each do |product| %>
    <div class="col-sm-4 col-xs-12">
      <div class="productBox">
        <div class="productImage clearfix">
          <%= image_tag product.display_image.attachment(:product) %>
          <div class="productMasking">
            <ul class="list-inline btn-group" role="group">
              <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
              <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
              <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
            </ul>
          </div>
        </div>
        <div class="productCaption clearfix">
          <a href="single_product.html">
            <h5><%= link_to product.name, potepan_product_path(product) %></h5>
          </a>
          <h3><%= product.display_price %></h3>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/_product_sidebar.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% taxonomies.each do |taxonomy| %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#taxon_<%= taxonomy.id %>"><%= taxonomy.name %><i class="fa fa-plus"></i></a>
            <ul id="taxon_<%= taxonomy.id %>" class="collapse collapseItem">
              <% taxonomy.root.children.each do |child| %>
                <% if child.leaf? %>
                  <li>
                    <%= link_to potepan_category_path(child.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i> <span><%= "#{child.name} (#{child.all_products.count})" %></span>
                    <% end %>
                  </li>
                <% else %>
                  <li>
                    <a href="javascript:;" data-toggle="collapse" data-target="#taxon_<%= child.id %>"><%= child.name %><i class="fa fa-plus"></i></a>
                    <ul id="taxon_<%= child.id %>" class="collapse collapseItem">
                      <% child.children.each do |grand_child| %>
                        <li class="indent-right">
                          <%= link_to potepan_category_path(grand_child.id) do %>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <span><%= "#{grand_child.name} (#{grand_child.all_products.count})" %></span>
                          <% end %>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="panel panel-default priceRange">
  <div class="panel-heading">値段から探す</div>
  <div class="panel-body clearfix">
    <div class="price-slider-inner">
      <span class="amount-wrapper">
        <input type="text" id="price-amount-1" readonly>
        <strong>-</strong>
        <input type="text" id="price-amount-2" readonly>
      </span>
      <div id="price-range"></div>
    </div>
    <input class="btn btn-default" type="submit" value="絞り込む">
    <!-- <span class="priceLabel">Price: <strong>12 円- 30<円/strong></span> -->
  </div>
</div>
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <li><a href="#">ブラック<span>(15)</span></a></li>
      <li><a href="#">ホワイト<span>(10)</span></a></li>
      <li><a href="#">レッド<span>(7)</span></a></li>
      <li><a href="#">ブルー<span>(12)</span></a></li>
      <li><a href="#">オレンジ<span>(12)</span></a></li>
    </ul>
  </div>
</div>
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <li><a href="#">S<span>(15)</span></a></li>
      <li><a href="#">M<span>(10)</span></a></li>
      <li><a href="#">L<span>(7)</span></a></li>
      <li><a href="#">XL<span>(12)</span></a></li>
    </ul>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<%= provide(:title, full_title(@taxon.name)) %>

<!-- TITLE LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <%= render 'light_section', taxon: @taxon %>
</section>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <%= render 'product_sidebar', taxonomies: @taxonomies %>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <%= render 'product_main', products: @products %>
      </div>
    </div>
  </div>
</section>

<!-- BRAND LIGHT SECTION -->
<section class="lightSection clearfix">
  <%= render 'shared/brand_logo' %>
</section>

app/views/potepan/products/_cart_form.html.erb
<% if product.has_variants? %>
  <span class="quick-drop">
    <%= select :guiest, :id3, options_text(product), {}, class: "select-drop" %>
  </span>
<% end %>
<span class="quick-drop resizeWidth">
  <%= select :guiest, :id4, quantities(product), {}, class: "select-drop" %>
</span>
<div class="btn-area">
  <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
</div>

app/views/potepan/products/_description.html.erb
<ul class="list-inline">
  <li>
    <%= link_to potepan_category_path(session[:taxon] || product.taxons.first.id) do %>
      <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
    <% end %>
  </li>
</ul>
<h2><%= product.name %></h2>
<h3><%= product.display_price %></h3>
<p><%= product.description %></p>

app/views/potepan/products/_image.html.erb
<div id="carousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% images.each_with_index do |image, index| %>
      <div class="item <%= "active" if index.zero? %>">
        <%= image_tag image.attachment(:product) %>
      </div>
    <% end %>
  </div>
</div>

app/views/potepan/products/_light_section.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <div class="page-title">
        <h2><%= product.name %></h2>
      </div>
    </div>
    <div class="col-xs-6">
      <ol class="breadcrumb pull-right">
        <li>
          <a href="index.html">Home</a>
        </li>
        <li class="active"><%= product.name %></li>
      </ol>
    </div>
  </div>
</div>

app/views/potepan/products/_property.html.erb
<div class="tabArea">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#details">details</a></li>
    <li><a data-toggle="tab" href="#about-art">about art</a></li>
    <li><a data-toggle="tab" href="#sizing">sizing</a></li>
    <li><a data-toggle="tab" href="#shipping">shipping</a></li>
  </ul>
  <div class="tab-content">
    <div id="details" class="tab-pane fade in active">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      <ul class="list-unstyled">
        <% product_properties.each do |product_property| %>
          <li><%= "#{product_property.property.presentation} : #{product_property.value}" %></li>
        <% end %>
      </ul>
    </div>
    <div id="about-art" class="tab-pane fade">
      <p>Nulla facilisi. Mauris efficitur, massa et iaculis accumsan, mauris velit ultrices purus, quis condimentum nibh dolor ut tortor. Donec egestas tortor quis mattis gravida. Ut efficitur elit vitae dignissim volutpat. </p>
    </div>
    <div id="sizing" class="tab-pane fade">
      <p>Praesent dui felis, gravida a auctor at, facilisis commodo ipsum. Cras eu faucibus justo. Nullam varius cursus nisi, sed elementum sem sagittis at. Nulla tellus massa, vestibulum a commodo facilisis, pulvinar convallis nunc.</p>
    </div>
    <div id="shipping" class="tab-pane fade">
      <p>Mauris lobortis augue ex, ut faucibus nisi mollis ac. Sed volutpat scelerisque ex ut ullamcorper. Cras at velit quis sapien dapibus laoreet a id odio. Sed sit amet accumsan ante, eu congue metus. Aenean eros tortor, cursus quis feugiat sed, vestibulum vel purus.</p>
    </div>
  </div>
</div>

app/views/potepan/products/_relation.html.erb
<div class="col-xs-12">
  <div class="page-header">
    <h4>関連商品</h4>
  </div>
</div>

<% related_products.each do |related_product| %>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag related_product.display_image.attachment(:product) %>
        <div class="productMasking">
          <ul class="list-inline btn-group" role="group">
            <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
            <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
            <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="productCaption clearfix">
        <%= link_to potepan_product_path(related_product) do %>
          <h5><%= related_product.name %></h5>
          <h3><%= related_product.display_price %></h3>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/potepan/products/_thumbnail.html.erb
<div class="clearfix">
  <div id="thumbcarousel" class="carousel slide" data-interval="false">
    <div class="carousel-inner">
      <% images.each_with_index do |image, index| %>
        <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb">
          <%= image_tag image.attachment(:small) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/products/show.html.erb
<%= provide(:title, full_title(@product.name)) %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <%= render 'light_section', product: @product %>
</section>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <%= render 'image', images: @images %>
            <%= render 'thumbnail', images: @images %>
          </div>
          <div class="media-body">
            <%= render 'description', product: @product %>
            <%= render 'cart_form', product: @product %>
            <%= render 'property', product_properties: @product_properties %>
          </div>
        </div>
      </div>
    </div>
    <div class="row productsContent">
      <%= render 'relation', related_products: @related_products %>
    </div>
  </div>
</section>

<%= render 'shared/product_modal' %>

app/views/potepan/sample/checkout_complete.html.erb
<%= provide(:title, full_title("Order Completed")) %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2>thanks message</h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="index.html">Home</a>
          </li>
          <li class="active">thanks message</li>
        </ol>
      </div>
    </div>
  </div>
</section>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix setp5">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="thanksContent">
          <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
          <h3>Shipping Details</h3>
          <div class="thanksInner">
            <div class="row">
              <div class="col-sm-6 col-xs-12 tableBlcok">
                <address>
                  <span>Shipping address:</span> <a href="mailto:adamsmith@bigbag.com">adamsmith@bigbag.com</a> <br>
                  <span>Email:</span> <a href="mailto:adamsmith@bigbag.com">adamsmith@bigbag.com</a> <br>
                  <span>Phone:</span> +884 5452 6432
                </address>
              </div>
              <div class="col-sm-6 col-xs-12">
                <div class="well">
                  <h2><small>Order ID</small>9547</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/sample/product_grid_left_sidebar.html.erb
<%= provide(:title, full_title("Product Grid Sidebar Left")) %>

<!-- TITLE LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <%= render 'light_section' %>
</section>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <%= render 'product_sidebar' %>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <%= render 'product_main' %>
      </div>
    </div>
  </div>
</section>

<!-- BRAND LIGHT SECTION -->
<section class="lightSection clearfix">
  <%= render 'shared/brand_logo' %>
</section>

app/views/shared/_brand_logo.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="owl-carousel partnersLogoSlider">
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-main navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(image_tag("img/logo.png", :alt => ""), potepan_path, class: "navbar-brand") %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', potepan_path %></li>
        <li class="dropdown megaDropMenu active">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
          <ul class="dropdown-menu row">
            <li class="col-sm-3 col-xs-12">
              <ul class="list-unstyled">
                <li>Products Grid View</li>
                <li><a href="product_grid_left_sidebar.html">Products Sidebar Left</a></li>
                <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                <li><a href="product-grid-4-col.html">Products 4 Columns</a></li>
              </ul>
            </li>
            <li class="col-sm-3 col-xs-12">
              <ul class="list-unstyled">
                <li>Products List View</li>
                <li><a href="product_list_left_sidebar.html">Products Sidebar Left</a></li>
                <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li>
                <li class="listHeading">Others</li>
                <li class="active"><a href="single_product.html">Single Product</a></li>
                <li><a href="cart_page.html">Cart Page</a></li>
              </ul>
            </li>
            <li class="col-sm-3 col-xs-12">
              <ul class="list-unstyled">
                <li>Checkout</li>
                <li><a href="checkout_step_1.html">Step 1 - Address</a></li>
                <li><a href="checkout_step_2.html">Step 2 - Shipping</a></li>
                <li><a href="checkout_step_3.html">Step 3 - Payment</a></li>
                <li><a href="checkout_step_4.html">Step 4 - Payment</a></li>
                <li><a href="checkout_complete.html">Order Complete</a></li>
              </ul>
            </li>
            <li class="col-sm-3 col-xs-12">
              <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
          <ul class="dropdown-menu dropdown-menu-left">
            <li><a href="about_us.html">About Us</a></li>
            <li><a href="signup.html">Register</a></li>
            <li><a href="signup-login.html">Register or Login</a></li>
            <li><a href="login.html">Login</a></li>
            <li><a href="lost-password.html">Password Recovery</a></li>
            <li><a href="privacy_policy.html">Privacy Policy</a></li>
            <li><a href="terms-and-conditions.html">Terms &amp; Conditions</a></li>
            <li><a href="404.html">404 Not Found</a></li>
            <li><a href="coming-soon.html">Coming Soon</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
          <ul class="dropdown-menu dropdown-menu-right">
            <li><a href="blog_right_sidebar.html">Right Sidebar</a></li>
            <li><a href="blog_left_sidebar.html">Left Sidebar</a></li>
            <li><a href="blog-fullwidth.html">Full Width</a></li>
            <li><a href="blog-single-fullwidth.html">Single Post</a></li>
            <li><a href="blog_single_right_sidebar.html">Single Right Sidebar</a></li>
            <li><a href="blog_single_left_sidebar.html">Single Left Sidebar</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
          <ul class="dropdown-menu dropdown-menu-right">
            <li><a href="account-dashboard.html">Dashboard</a></li>
            <li><a href="account-profile.html">Profile</a></li>
            <li><a href="account-all-orders.html">All Orders</a></li>
            <li><a href="account-single-order.html">Single Order</a></li>
            <li><a href="account-wishlist.html">Wishlist</a></li>
            <li><a href="account-address.html">Address</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>